### ISSUE TITLE
error: reference to non-static member function must be called; did you mean to call it with no arguments?

### ISSUE THREAD

**Issue by moyans** [nihui/ncnn-android-benchmark#4]
用 ncnn-20210507-android-vulkan 来编译会报错
ncnn-android-benchmark\app\src\main\jni\benchmarkncnn_jni.cpp:54:34: error: reference to non-static member function must be called; did you mean to call it with no arguments?

**Comment by ghost** [comment]
> 用 ncnn-20210507-android-vulkan 来编译会报错
> ncnn-android-benchmark\app\src\main\jni\benchmarkncnn_jni.cpp:54:34: error: reference to non-static member function must be called; did you mean to call it with no arguments?

layers改成layers()
blobs改成blobs()就可以
